services:
  resell-api:
    container_name: resell-api
    restart: always
    image: node:20.10.0
    environment:
      - TZ=Asia/Seoul
    ports:
      - 4001:3010
    volumes:
      - ./:/usr/src/resell
    working_dir: /usr/src/resell

    networks:
      - monorepo-network

    command: bash -c "npm install && npm run build && npm run start:prod"

  resell-batch:
    container_name: resell-batch
    restart: unless-stopped
    image: node:20.10.0
    environment:
      - TZ=Asia/Seoul
    ports:
      - 4002:3011
    volumes:
      - ./:/usr/src/resell
    working_dir: /usr/src/resell

    networks:
      - monorepo-network

    command: bash -c "npm install && npm run build && npm run start:prod:batch"



networks:
  monorepo-network:
    driver: bridge


#resell-next localhost  4000 -> container: 3000
#resell-api localhost   4001 -> container: 3010
#resell-batch localhost 4002 -> container: 3011